---
meta:
    description:
        Creates a managed NAT
    parameters:
        custom_resource_function:
            description:
                The Lambda function that backs the Firehose custom resource
            value:
                ref:
                    parser: lambda
                    parameters:
                        path: lambda_function
